/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "docs",
  "tagline": "Welcome to Egypt Studio \n    The goal : programming new things that affect the community of the fivem or more, and other things",
  "url": "https://egypt-studios-docs.vercel.app",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/logo.png",
  "organizationName": "egypt studios",
  "projectName": "egypt studios documintation",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    [
      "D:\\egypt-studios-docs\\node_modules\\docusaurus-plugin-search-local\\dist\\server\\index.js",
      {
        "indexDocs": true,
        "indexBlog": true,
        "indexPages": false,
        "docsRouteBasePath": "/",
        "blogRouteBasePath": "/blog",
        "hashed": false,
        "highlightSearchTermsOnTargetPage": true
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "qbscripts",
        "path": "qbscripts",
        "routeBasePath": "qbscripts",
        "sidebarPath": "D:\\egypt-studios-docs\\sidebars.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "standalonescripts",
        "path": "standalonescripts",
        "routeBasePath": "standalonescripts",
        "sidebarPath": "D:\\egypt-studios-docs\\sidebars.js"
      }
    ]
  ],
  "themeConfig": {
    "metadata": [
      {
        "property": "og:image",
        "content": "https://egypt-studios-docs.vercel.app/img/egypt-studios.png"
      }
    ],
    "navbar": {
      "hideOnScroll": true,
      "logo": {
        "alt": "egypt studios",
        "src": "img/logo.png"
      },
      "items": [
        {
          "type": "dropdown",
          "label": "FiveM",
          "position": "left",
          "items": [
            {
              "to": "/esxscripts/intro",
              "label": "esx scripts",
              "activeBaseRegex": "/esxscripts/"
            }
          ]
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "to": "/rules",
          "label": "Rules",
          "position": "left"
        },
        {
          "href": "https://egyptstudio.tebex.io/category/2031240",
          "label": "Shop Now",
          "position": "right"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Society",
          "items": [
            {
              "label": "discord",
              "href": "https://discord.gg/2Xhag8k8Pm"
            },
            {
              "label": "youtube",
              "href": "https://www.youtube.com/c/Konar1"
            }
          ]
        },
        {
          "title": "Donation",
          "items": [
            {
              "label": "Paypal",
              "href": "https://www.paypal.com/paypalme/KonarEG"
            },
            {
              "label": "Ko-fi",
              "href": "https://ko-fi.com/konarplus/"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 💗 egypt studios "
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "routeBasePath": "esxscripts",
          "path": "esxscripts",
          "sidebarPath": "D:\\egypt-studios-docs\\sidebars.js",
          "lastVersion": "current",
          "onlyIncludeVersions": [
            "current"
          ]
        },
        "blog": {
          "showReadingTime": true
        },
        "theme": {
          "customCss": "D:\\egypt-studios-docs\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
